### ISSUE TITLE
[Smart Contracts] Setup Contract Build Pipeline

### ISSUE THREAD

**Issue by KamesCG** [rapid-eth/rapid-adventures#34]
Smart contract Build artifacts (bytecode/abi) should be generated in `src/contracts/` via the `contracts` folder.

Let's use Embark to manage contract compiling.

https://embark.status.im/docs/configuration.html

**Comment by onpaws** [comment]
Tues Nov 19 - meeting with Joe/Kames/Patrick - decided to use Joe's repos/solc vs embark

**Comment by onpaws** [comment]
I installed Geth & IPFS per the docs.  
RN am seeing some 
```
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/fsevents-9e343445/node_modules/abbrev' -> '/usr/local/lib/node_modules/.staging/abbrev-101b1ffa'

npm ERR! code EPERM
npm ERR! syscall spawn
npm ERR! errno EPERM
npm ERR! Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
npm ERR!  OperationalError: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!   cause: Error: spawn EPERM
npm ERR!       at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!       at spawn (child_process.js:540:9)
npm ERR!       at execFile (child_process.js:224:17)
npm ERR!       at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!       at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:16:23)
npm ERR!       at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!       at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!     errno: 'EPERM',
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'spawn'
npm ERR!   },
npm ERR!   stack: 'Error: spawn EPERM\n' +
npm ERR!     '    at ChildProcess.spawn (internal/child_process.js:394:11)\n' +
npm ERR!     '    at spawn (child_process.js:540:9)\n' +
npm ERR!     '    at execFile (child_process.js:224:17)\n' +
npm ERR!     '    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n' +
npm ERR!     '    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:16:23)\n' +
npm ERR!     '    at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)\n' +
npm ERR!     '    at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24',
npm ERR!   errno: 'EPERM',
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'spawn',
npm ERR!   parent: 'embark'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paws/.npm/_logs/2019-11-19T16_21_14_018Z-debug.log
```
